### ISSUE TITLE
有关计算损失的问题

### ISSUE THREAD

**Issue by plf1999** [caolinfeng/OoDHDR-codec#1]
distortion1 = 1 - ms_ssim(255*env_sdr, 255*re_sdr)
        penalty1 = penalty(255*re_sdr, 255*env_sdr, flag_hdr=False) 
        请问计算上述损失项为什么要将输入图像乘上255，因为我看论文并没有这样做。并且奇怪的是我在复现时出现下面的报错，应该也是在上面损失项出现错误，导致在反向传播出现了NaN。而我在上面损失项改为图像不乘上255，代码就不报错了，但是训练了250epoch后进行测试发现重建图像质量很差。请问是什么原因，期待你的回复，谢谢！
 File "train_ood.py", line 539, in <module>
    main(sys.argv[1:])
  File "train_ood.py", line 504, in main
    args.pw
  File "train_ood.py", line 203, in train_one_epoch
    out_criterion = criterion(epoch, out_net, N*B, sdr, hdr, penalty_weight, regu_weight)
  File "/data/plf/anaconda3/envs/swin/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "train_ood.py", line 69, in forward
    penalty1 = penalty(255*re_sdr, 255*env_sdr, flag_hdr=False)
  File "train_ood.py", line 157, in penalty
    loss = 1 - ms_ssim(img, re_img * scale)
  File "/data/plf/anaconda3/envs/swin/lib/python3.7/site-packages/pytorch_msssim/ssim.py", line 225, in ms_ssim
    ms_ssim_val = torch.prod(mcs_and_ssim ** weights.view(-1, 1, 1), dim=0)
  File "/data/plf/anaconda3/envs/swin/lib/python3.7/site-packages/torch/_tensor.py", line 39, in wrapped
    return f(*args, **kwargs)
  File "/data/plf/anaconda3/envs/swin/lib/python3.7/site-packages/torch/fx/traceback.py", line 57, in format_stack
    return traceback.format_stack()
 (Triggered internally at ../torch/csrc/autograd/python_anomaly_mode.cpp:121.)
  allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "train_ood.py", line 539, in <module>
    main(sys.argv[1:])
  File "train_ood.py", line 504, in main
    args.pw
  File "train_ood.py", line 204, in train_one_epoch
    out_criterion["loss"].backward()
  File "/data/plf/anaconda3/envs/swin/lib/python3.7/site-packages/torch/_tensor.py", line 489, in backward
    self, gradient, retain_graph, create_graph, inputs=inputs
  File "/data/plf/anaconda3/envs/swin/lib/python3.7/site-packages/torch/autograd/__init__.py", line 199, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: Function 'MulBackward0' returned nan values in its 0th output.

**Comment by caolinfeng** [comment]
Thanks for your feedback.

Unfortunately, I cannot determine exactly where the problem lies given the limited information in this posted Error Log.

Actually the MS-SSIM function utilized in our code is compatible to both [0,1] and [0,255] scaled image inputs. Both types of input scales yield identical MS-SSIM distortion values and generate similar gradient norm penalty terms. So I think either input scale (1 or 255) is suitable for model training and testing.

Regarding the issue you mentioned, if the error is occurring due to NaN output from the MS-SSIM computation, you can address it by using normalized MS-SSIM. This can be achieved by setting the optional parameter "normalize=True" in the "msssim" function during the initial few dozen epochs of training. However, it may slow down the convergence rate of the training process.

Due to the limited information in the posted log, it may be challenging to identify the exact problem. If you have further questions or need assistance, you can reach out to me via email [cao.1378@osu.edu] to provide more details about this issue, or we can schedule a virtual meeting if you prefer. I hope this helps.

**Comment by plf1999** [comment]
非常感谢您的解答。我的问题已经解决了，原因是我安装的pytorch-msssim库与您代码中的不一致，甚至没有normalize参数，应该是pypi上的pytorch-msssim库更新了，我从
pypi 上找到msssim库的参考链接  GitHub - jorge-pessoa/pytorch-msssim：PyTorch
可微多尺度结构相似性 （MS-SSIM） 损失 <https://github.com/jorge-pessoa/pytorch-msssim>
（应该是当时您使用的msssim库），并下载到我代码里，代码成功运行，没有报错，期待得到很好的实验结果。再次感谢！

**Comment by plf1999** [comment]
你好，我还有个问题，请问您用于实验结果对比的几个HDR压缩方法代码是在哪里找到的？例如TMO+BPG,TMO+WEBP,Mai2011，我并没有找到这些方法的开源代码。

**Comment by caolinfeng** [comment]
[新建文件夹.zip](https://github.com/caolinfeng/OoDHDR-codec/files/11910773/default.zip)

These baselines are implemented by ourselves. I have uploaded a zip file containing the implementations of two representative HDR compression frameworks: TMO+H264 [Mai 2021] and Jpeg+RI. Additionally, I have provided a library of ffmpeg, which includes official compression tools like JPEG and H.264, in case you need them. However, please note that due to different environment configurations and library updates, I cannot guarantee successful compilation or execution on your computer. If you encounter any issues, please replace the package and the corresponding compression parts (line #91-#94 in the main.py document) in the code with your own properly configured official compression toolkits.

If you wish to conduct other compression beselines within the TMO+H264 framework, you can import their corresponding libraries (e.g., WebP, BPG) and replace the H264 compression codes (line #91-#94 in the main.py document) to implement these baselines. Unfortunately, some of these packages and codes are no longer available or lost, so I'm unable to directly provide their code implementations. You may need to implement them yourself. Hope this helps.

**Comment by caolinfeng** [comment]
[Uploading Baselines.zip…]()

These baselines are implemented by ourselves. I have uploaded a zip file containing the implementations of two representative HDR compression frameworks: TMO+H264 [Mai 2021] and Jpeg+RI. Additionally, I have provided a library of ffmpeg, which includes official compression tools like JPEG and H.264, in case you need them. However, please note that due to different environment configurations and library updates, I cannot guarantee successful compilation or execution on your computer. If you encounter any issues, please replace the package and the corresponding compression parts (line #91-#94 in the main.py document) in the code with your own properly configured official compression toolkits.

If you wish to conduct other compression beselines within the TMO+H264 framework, you can import their corresponding libraries (e.g., WebP, BPG) and replace the H264 compression codes (line #91-#94 in the main.py document) to implement these baselines. Unfortunately, some of these packages and codes are no longer available or lost, so I'm unable to directly provide their code implementations. You may need to implement them yourself. Hope this helps.

**Comment by caolinfeng** [comment]
[Baselines.zip](https://github.com/caolinfeng/OoDHDR-codec/files/11911561/Baselines.zip)

These baselines are implemented by ourselves. I have uploaded a zip file containing the implementations of two representative HDR compression frameworks: TMO+H264 [Mai 2021] and Jpeg+RI. Additionally, I have provided a library of ffmpeg, which includes official compression tools like JPEG and H.264, in case you need them. However, please note that due to different environment configurations and library updates, I cannot guarantee successful compilation or execution on your computer. If you encounter any issues, please replace the package and the corresponding compression parts (line #91-#94 in the main.py document) in the code with your own properly configured official compression toolkits.

If you wish to conduct other compression beselines within the TMO+H264 framework, you can import their corresponding libraries (e.g., WebP, BPG) and replace the H264 compression codes (line #91-#94 in the main.py document) to implement these baselines. Unfortunately, some of these packages and codes are no longer available or lost, so I'm unable to directly provide their code implementations. You may need to implement them yourself. Hope this helps.

**Comment by smileto1** [comment]
您好，在这篇论文中如何设置压缩质量呢？

**Comment by caolinfeng** [comment]
By setting different hyper-parameter values of "--lambda" in the code for compression rate control.
